### PR TITLE
Defining Possible States of the Fusion Power Plant

### PR DESCRIPTION
**Pull request by dean-krueger**
Added temporary comments to the code to lay out the general states of the fusion power plant facility. The code below each comment, combined with the comment itself should hopefully be descriptive enough to start the discussion on the different states of the facility.

This PR closes issue #5

### CODE REVIEW

**Comment by gonuke** [comment]
I think this issue was probably poorly defined on my part.  It should probably focus on what causes a change of state since I think the states are largely well defined by #10.

**Comment by dean-krueger** [comment]
Changed the PR around a bit to better match the updated requirements. Also: differentiated between the initial startup condition and the operating condition, since the initial startup condition has that whole bit with the startup inventory requirement being different than the operating inventory requirement.

**Comment by gonuke** [comment]
Sorry for changing the target too much/again... but I think you can start actually coding the functions that you call to do the tests, i.e. moving away from pseudo-code to real code.

**Comment by dean-krueger** [comment]
Sounds good. I'll start with the check functions, but do you also mean that i should do all the other ones (ie `SequesterTritium()`, `OperateReactor()`, etc)?

**Comment by gonuke** [comment]
Just the check functions

**Comment by dean-krueger** [comment]
Going to close this PR for now, since the goals have changed so much. I think this is going to make more sense if we circle back around to it after some other stuff gets merged in (I think that's how this works, at least)

**Pull request closed without merging**
